### PR TITLE
added Flashforge Adventure 3 machine preset

### PR DESCRIPTION
**Pull request by rsnodgrass**

### CODE REVIEW

**Review by DRIgnazGortngschirl — COMMENTED** [review]
Hi @rsnodgrass,

rhank you for sharing the machine profile. I noticed that a specific host is set, which may need to be changed if someone else with a different printer IP wants to use it. Do you mind or would recomend setting this e.g to x.x.x.x to easily notice that this needs to be chnaged ?

**Review by DRIgnazGortngschirl — COMMENTED** [review]
Thanks for the update in the README and to the fillament profile!

**Comment by rsnodgrass** [comment]
@DRIgnazGortngschirl good idea! I changed to X.X.X.X as the example IP address. I had picked a 192.168.1.xxx address originally as a common default.

I also add a LICENSE.md file to be clear what the license was on using all these data files. Since these are community profiles and we want to encourage as much contribution and use (including commercial) as possible, the Creative-Commons Zero (CC0) license seems to be the least restrictive. Your thoughts would be great.

See more here:
https://ufal.github.io/public-license-selector/

**Comment by DRIgnazGortngschirl** [comment]
Awesome, thanks for adding the LICENSE.md file,  feel good about that choice of license!

Lets go for the merge.

**Pull request merged**
